# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G

# Fabric Properties
minecraft_version=26.3
loader_version=0.19.5

# Mod Properties
mod_version=1.8.7
maven_group=me.wesley1808
archives_base_name=advancedchat

# API dependencies
fabric_version=0.160.5+26.3
placeholder_api_version=3.2.0+26.3
playerdata_api_version=0.11.0+26.2
predicate_api_version=0.10.0+26.3

# Other dependencies
styledchat_version=2.14.0+26.3
vanish_version=1.6.15+26.2
